// Tests for scripts/brain-repair.mjs — the one-time cleanup for facts already corrupted by the OLD
// asymmetric Chronos serializer (writer JSON-escaped, parser didn't unescape → backslashes
// compounded n → 2n+1 on every write of ANY fact in the same note).
//
// The load-bearing property is EXACT RECOVERY WITH PROOF: every collapse step re-applies the
// historical lossy cycle and must reproduce the input byte-for-byte, so the repair can never guess.
// All fixtures are local; nothing here touches the live brain.
// Run: node --test lib/server/brainRepair.test.mjs

import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  historicalCycle, uncorruptOnce, collapseEscapes, diagnoseValue,
  diagnoseNote, repairNoteText, looksPathological,
} from '../../scripts/brain-repair.mjs';
import { applyFact } from './writeFact.js';
import { parseFrontmatter, normalizeFacts } from './memoryGraph.js';

const factsOf = (text, note = 'n.md') => normalizeFacts(parseFrontmatter(text).data, note).facts;

// The value that is really corrupted in the brain today (Seen resume PDF export / watermark_policy).
const INTENDED = 'The "Optimized with Seen · seenjobs.io" PDF footer is mandatory on every free-tier export';

// A REAL corrupted sample: the verbatim `object:` line the OLD writer+parser pair produced for
// INTENDED after the note was written 8 more times — 1022 backslashes in the raw line, the same
// shape now sitting in the brain. (Generated by running the pre-fix writeFact.js/memoryGraph.js
// pair from commit 6af7349, not hand-written.)
const CORRUPTED_LINE = "object: \"The \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"Optimized with Seen · seenjobs.io\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\" PDF footer is mandatory on every free-tier export\"";

const HOSTILE = [
  'The "Optimized with Seen · seenjobs.io" PDF footer',
  "it's a 'quoted' phrase",
  'C:\\Users\\brandon\\resume.pdf',
  'ratio: 3:1 — measured',
  '[[environment]] and [array, like]',
  'newline\nliteral\ttab',
  'café ✓ — résumé · naïve',
  'has # hash and "quote" together',
  '{"json":"blob","n":[1,2]}',
];

// ---------------------------------------------------------------------------
// The corruption model itself
// ---------------------------------------------------------------------------

test('historicalCycle reproduces the compounding law (n → 2n+1 backslashes per quote)', () => {
  let s = 'a "b"';
  const counts = [];
  for (let i = 0; i < 6; i++) { s = historicalCycle(s); counts.push((s.match(/\\/g) || []).length); }
  assert.deepEqual(counts, [2, 6, 14, 30, 62, 126], 'two quotes → 2·(2^k − 1) backslashes');
});

// ---------------------------------------------------------------------------
// Exact recovery, N = 1..6 cycles
// ---------------------------------------------------------------------------

for (let n = 1; n <= 6; n++) {
  test(`collapseEscapes recovers the exact original after ${n} escape cycle(s)`, () => {
    for (const original of HOSTILE) {
      let corrupted = original;
      for (let i = 0; i < n; i++) corrupted = historicalCycle(corrupted);
      const { value, cycles } = collapseEscapes(corrupted);
      assert.equal(value, original, `n=${n} failed for ${JSON.stringify(original)}`);
      // Values holding no `"` and no `\` are immune — the cycle is the identity on them.
      if (corrupted === original) assert.equal(cycles, 0, 'nothing escaped → nothing to collapse');
      else assert.ok(cycles >= 1 && cycles <= n, `n=${n}: implausible cycle count ${cycles}`);
    }
  });
}

test('uncorruptOnce PROVES each step — it refuses non-canonical escaping instead of guessing', () => {
  assert.equal(uncorruptOnce('a \\"b\\"'), 'a "b"');       // canonical: accepted
  assert.equal(uncorruptOnce('a\\/b'), null);              // \/ is legal JSON but never emitted
  assert.equal(uncorruptOnce('a\\u0041b'), null);          // \uXXXX for a printable: not canonical
  assert.equal(uncorruptOnce('a"b'), null);                // raw quote: not parseable
  assert.equal(uncorruptOnce('a\\'), null);                // lone trailing backslash
});

test('collapse is a fixed point — repairing an already-clean value is a no-op', () => {
  for (const v of HOSTILE) {
    assert.equal(collapseEscapes(v).value, v);
    assert.equal(diagnoseValue(v).after, v);
  }
});

// ---------------------------------------------------------------------------
// Conservatism: never guess (CLAUDE.md rule 5)
// ---------------------------------------------------------------------------

test('values with no compounding signature are left completely alone', () => {
  for (const v of ['plain prose', 'a \\n literal backslash-n', 'C:\\Users\\x', 'no escapes at all']) {
    assert.equal(looksPathological(v), false, v);
    assert.equal(diagnoseValue(v).status, 'clean', v);
  }
});

test('non-invertible escaping is reported as ambiguous and SKIPPED, never guessed', () => {
  for (const v of ['a\\\\q"b', '\\\\\\', 'x\\\\y"z"']) {
    const d = diagnoseValue(v);
    assert.equal(d.status, 'ambiguous', v);
    assert.equal(d.after, v, 'ambiguous values must be returned unchanged');
    assert.ok(d.reason, 'ambiguous findings must carry a reason');
  }
});

test('a single \\" (one lossy cycle OR an intentional literal) is REVIEW, not auto-repaired', () => {
  const d = diagnoseValue('say \\"hi\\"');
  assert.equal(d.status, 'review');
  assert.equal(d.after, 'say "hi"', 'the candidate repair is still computed for the report');
  assert.match(d.reason, /intentional literal backslash/);

  const note = applyFactWithRawObject('say \\"hi\\"');
  assert.equal(repairNoteText(note, 'n.md').changed, 0, 'review rows are not applied by default');
  assert.equal(repairNoteText(note, 'n.md', { includeSingleCycle: true }).changed, 1, 'opt-in applies them');
});

test('compounded runs (>=2 backslashes) ARE certain corruption and auto-repair', () => {
  const d = diagnoseValue(historicalCycle(historicalCycle('a "b"')));
  assert.equal(d.status, 'repaired');
  assert.equal(d.after, 'a "b"');
  assert.equal(d.cycles, 2);
});

// ---------------------------------------------------------------------------
// The real corrupted sample
// ---------------------------------------------------------------------------

test('REGRESSION: the real 1022-backslash brain sample repairs to the exact intended value', () => {
  assert.equal((CORRUPTED_LINE.match(/\\/g) || []).length, 1022, 'fixture must be the real multi-hundred-backslash line');
  assert.match(CORRUPTED_LINE, /^object: "/, 'fixture must be a verbatim frontmatter line');

  // Read it exactly as the (fixed) parser now does, then repair.
  const note = [
    '---', 'title: claude observations', 'updated: 2026-07-13', 'facts:',
    '  - id: seen-resume-pdf-export-watermark-policy-20260705-0',
    '    subject: Seen resume PDF export',
    '    predicate: watermark_policy',
    `    ${CORRUPTED_LINE}`,
    '    valid_from: 2026-07-05', '    valid_to: null', '    confidence: high',
    '---', '', '# body stays', '',
  ].join('\n');

  // The fixed parser undoes exactly ONE escape layer per read (1022 → 510); the remaining
  // compounding is historical damage that only this repair can remove.
  const stored = factsOf(note)[0].object;
  assert.equal((stored.match(/\\/g) || []).length, 510, 'still deeply corrupted after one parse');

  const d = diagnoseValue(stored);
  assert.equal(d.status, 'repaired');
  assert.equal(d.after, INTENDED, 'must recover the intended value byte-for-byte');

  // …and the repaired note round-trips cleanly from then on.
  const { text: fixed, changed } = repairNoteText(note, 'claude-observations.md');
  assert.equal(changed, 1);
  assert.equal(factsOf(fixed)[0].object, INTENDED);
  assert.match(fixed, /# body stays/, 'body preserved');
  assert.match(fixed, /title: claude observations/, 'other frontmatter preserved');
  assert.ok(!/\\{2,}/.test(fixed), 'no compounded run remains');

  const after = applyFact(fixed, 'claude-observations.md', { subject: 'Seen', predicate: 'later', object: 'write' }, '2026-07-14');
  assert.equal(factsOf(after)[0].object, INTENDED, 'stays repaired across a later write');
});

test('diagnoseNote reports per-field findings and leaves healthy notes untouched', () => {
  const healthy = applyFact('', 'n.md', { subject: 'Seen', predicate: 'mrr', object: '$0 — "pre-revenue"' }, '2026-07-01');
  const { findings, changed } = diagnoseNote(healthy, 'n.md');
  assert.deepEqual(findings, []);
  assert.equal(changed, 0);
  assert.equal(repairNoteText(healthy, 'n.md').text, null, 'no rewrite when nothing to repair');
});

// Build a note whose stored object is the given RAW (already-corrupted) string.
function applyFactWithRawObject(raw) {
  return [
    '---', 'title: n', 'facts:',
    '  - id: s-p-20260701-0', '    subject: S', '    predicate: p',
    `    object: ${JSON.stringify(raw)}`, // JSON-quoted so the parser reads back `raw` verbatim
    '    valid_from: 2026-07-01', '    valid_to: null',
    '---', '', 'body', '',
  ].join('\n');
}
