-- Career Intelligence Pipeline
-- Three-layer data architecture:
-- 1. resume_skills: per-user skill extraction (private, user-linked)
-- 2. career_signals: anonymized market signals (no user_id, service-role only)
-- 3. market_insights: Claude-synthesized intelligence (generated, not aggregated)
--
-- The synthesis layer is the moat — competitors can aggregate raw data,
-- but cannot replicate what Claude generates from Seen's unique combination of
-- resume skills + application outcomes + company behavior.

-- ─── Layer 1: Per-user resume skills (private) ─────────────────────────────
-- Stores extracted skills, seniority, and function — linked to user
CREATE TABLE IF NOT EXISTS resume_skills (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  skills        text[]      NOT NULL DEFAULT '{}',
  seniority     text,                         -- junior / mid / senior / staff / principal / executive
  function      text,                         -- engineering / design / product / marketing / sales / ops / data / finance / legal / other
  years_exp     smallint,
  top_titles    text[]      DEFAULT '{}',     -- last 3 role titles from employment history
  updated_at    timestamptz DEFAULT now(),
  created_at    timestamptz DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_resume_skills_user ON resume_skills(user_id);
ALTER TABLE resume_skills ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='resume_skills' AND policyname='own_skills') THEN
    CREATE POLICY "own_skills" ON resume_skills
      USING (auth.uid() = user_id)
      WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;

-- ─── Layer 2: Anonymized career signals (service-role only) ────────────────
-- One snapshot per resume parse. No user_id — used only for aggregate analysis.
-- Contains just enough signal to be statistically useful, never enough to re-identify.
CREATE TABLE IF NOT EXISTS career_signals (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  skills        text[]      NOT NULL DEFAULT '{}',
  seniority     text,
  function      text,
  years_exp     smallint,
  created_at    timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_career_signals_created ON career_signals(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_career_signals_function ON career_signals(function);
ALTER TABLE career_signals ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='career_signals' AND policyname='career_signals_service_only') THEN
    CREATE POLICY "career_signals_service_only" ON career_signals
      FOR ALL
      USING (auth.role() = 'service_role')
      WITH CHECK (auth.role() = 'service_role');
  END IF;
END $$;

-- Application outcome signals — links skill patterns to real outcomes (no user_id)
CREATE TABLE IF NOT EXISTS application_outcome_signals (
  id                uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  career_signal_id  uuid        REFERENCES career_signals(id) ON DELETE SET NULL,
  skills_snapshot   text[]      NOT NULL DEFAULT '{}',  -- denormalized for query performance
  seniority         text,
  function          text,
  company_name      text,
  role_title        text,
  outcome           text        NOT NULL CHECK (outcome IN ('ghosted','rejected','interview','hired')),
  days_to_response  smallint,
  created_at        timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_outcome_signals_outcome   ON application_outcome_signals(outcome);
CREATE INDEX IF NOT EXISTS idx_outcome_signals_function  ON application_outcome_signals(function);
CREATE INDEX IF NOT EXISTS idx_outcome_signals_created   ON application_outcome_signals(created_at DESC);
ALTER TABLE application_outcome_signals ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='application_outcome_signals' AND policyname='outcome_signals_service_only') THEN
    CREATE POLICY "outcome_signals_service_only" ON application_outcome_signals
      FOR ALL
      USING (auth.role() = 'service_role')
      WITH CHECK (auth.role() = 'service_role');
  END IF;
END $$;

-- ─── Layer 3: Claude-synthesized market intelligence (proprietary) ──────────
-- This is the moat. Generated by Claude from career_signals + outcome_signals.
-- Not raw aggregation — synthesized insights that cannot be reverse-engineered.
CREATE TABLE IF NOT EXISTS market_insights (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  insight_type  text        NOT NULL,  -- 'skills_demand' | 'career_paths' | 'ghost_patterns' | 'weekly_brief'
  function      text,                  -- null = cross-function
  data          jsonb       NOT NULL,
  generated_at  timestamptz DEFAULT now(),
  signal_count  int         DEFAULT 0  -- how many signals went into this generation
);
CREATE INDEX IF NOT EXISTS idx_market_insights_type ON market_insights(insight_type, generated_at DESC);
ALTER TABLE market_insights ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='market_insights' AND policyname='market_insights_readable') THEN
    -- Insights are readable by all authenticated users (they're already anonymized/synthesized)
    CREATE POLICY "market_insights_readable" ON market_insights
      FOR SELECT
      USING (true);
    CREATE POLICY "market_insights_service_write" ON market_insights
      FOR ALL
      USING (auth.role() = 'service_role')
      WITH CHECK (auth.role() = 'service_role');
  END IF;
END $$;

-- ─── Career transitions (anonymized, no user_id) ────────────────────────────
-- Tracks from_title → to_title transitions for career path intelligence
CREATE TABLE IF NOT EXISTS career_transitions (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  from_title  text,
  to_title    text        NOT NULL,
  function    text,
  years_in_prior_role smallint,
  created_at  timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_transitions_to_title ON career_transitions(to_title);
CREATE INDEX IF NOT EXISTS idx_transitions_from_title ON career_transitions(from_title);
ALTER TABLE career_transitions ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='career_transitions' AND policyname='transitions_service_only') THEN
    CREATE POLICY "transitions_service_only" ON career_transitions
      FOR ALL
      USING (auth.role() = 'service_role')
      WITH CHECK (auth.role() = 'service_role');
  END IF;
END $$;
